platform :ios, '11.0'
use_frameworks!
install! 'cocoapods', generate_multiple_pod_projects: true, disable_input_output_paths: true

target 'BlockChainKit_Example' do
  pod 'BlockChainKit', :path => '../'

  target 'BlockChainKit_Tests' do
    inherit! :search_paths
    
  end
end
