platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'BlockChainKit_Example' do
  pod 'BlockChainKit', :path => '../'

  target 'BlockChainKit_Tests' do
    inherit! :search_paths
    
  end
end
